# Generated by Django 5.2.6 on 2025-12-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bank_account_name_user_bank_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kra_pin_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id_image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proof_of_ownership_url',
        ),
        migrations.AddField(
            model_name='user',
            name='kra_pin',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/kra_pins/'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/national_ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='proof_of_ownership',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/ownership_docs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LANDLORD', 'Landlord'), ('TENANT', 'Tenant')], max_length=20),
        ),
    ]
