# Generated by Django 5.0.4 on 2026-02-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_kra_pin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LANDLORD', 'Landlord'), ('TENANT', 'Tenant'), ('AGENT', 'Agent')], max_length=20),
        ),
    ]
