# Generated by Django 5.2.6 on 2026-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_branch_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kra_pin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proof_of_ownership',
        ),
        migrations.RemoveField(
            model_name='user',
            name='terms_accepted',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
