# Generated by Django 5.0.4 on 2026-02-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
        ('users', '0008_remove_user_bank_account_name_and_more'),
    ]

    operations = [
    ]
