# Generated by Django 5.0.4 on 2026-03-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20260223_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_request_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_request_window',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
