# Generated by Django 6.0.2 on 2026-03-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20260223_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='physical_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
