# Generated by Django 6.0.2 on 2026-03-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_physical_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proof_of_ownership',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/proof_of_ownership/'),
        ),
    ]
