# Generated by Django 6.0.2 on 2026-03-18 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('report', models.TextField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='properties.apartment')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verification_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='verification.verification')),
            ],
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['status'], name='verificatio_status_94997c_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['assigned_agent'], name='verificatio_assigne_4f42f7_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['apartment'], name='verificatio_apartme_2e0890_idx'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ASSIGNED', 'IN_PROGRESS'])), fields=('apartment',), name='unique_active_verification_per_apartment'),
        ),
    ]
