# Generated by Django 5.0.4 on 2026-02-20 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_apartment_is_approved'),
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ASSIGNED', 'IN_PROGRESS'])), fields=('apartment',), name='unique_active_verification_per_apartment'),
        ),
    ]
