# Generated by Django 6.0.2 on 2026-03-18 04:09

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentAmenityDistance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amenity_type', models.CharField(choices=[('SCHOOL', 'School'), ('MARKET', 'Market'), ('HOSPITAL', 'Hospital'), ('ROAD', 'Road'), ('BUS_STOP', 'Bus Stop'), ('PHARMACY', 'Pharmacy'), ('BANK', 'Bank'), ('RESTAURANT', 'Restaurant'), ('PARK', 'Park'), ('GYM', 'Gym'), ('UNIVERSITY', 'University'), ('SHOPPING_MALL', 'Shopping Mall')], max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nearest_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['amenity_type'],
            },
        ),
        migrations.CreateModel(
            name='KeyAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amenity_type', models.CharField(choices=[('SCHOOL', 'School'), ('MARKET', 'Market'), ('HOSPITAL', 'Hospital'), ('ROAD', 'Road'), ('BUS_STOP', 'Bus Stop'), ('PHARMACY', 'Pharmacy'), ('BANK', 'Bank'), ('RESTAURANT', 'Restaurant'), ('PARK', 'Park'), ('GYM', 'Gym'), ('UNIVERSITY', 'University'), ('SHOPPING_MALL', 'Shopping Mall')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Key Amenities',
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='lease_agreements/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_hash', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='tenant_documents/')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_on', models.DateTimeField(auto_now_add=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number_or_id', models.CharField(max_length=100)),
                ('category', models.CharField(default='RESIDENTIAL', max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Maintenance')], default='VACANT', max_length=20)),
                ('interior_images', models.JSONField(blank=True, default=list)),
                ('exterior_images', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('last_status_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['apartment', 'unit_number_or_id'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('overview_description', models.TextField(blank=True)),
                ('exterior_image_url', models.URLField(blank=True)),
                ('rules_and_policies', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('occupied_units', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='apartments', to='properties.amenity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
