# Generated by Django 5.0.4 on 2025-10-27 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('overview_description', models.TextField(blank=True)),
                ('exterior_image_url', models.URLField(blank=True)),
                ('lease_agreement_document_url', models.URLField(blank=True)),
                ('rules_and_policies', models.TextField(blank=True)),
                ('verification_status', models.CharField(default='PENDING', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('occupied_units', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='apartments', to='properties.amenity')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number_or_id', models.CharField(max_length=100)),
                ('category', models.CharField(default='RESIDENTIAL', max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Maintenance')], default='VACANT', max_length=20)),
                ('interior_images', models.JSONField(blank=True, default=list)),
                ('exterior_images', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('last_status_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.apartment')),
            ],
            options={
                'ordering': ['apartment', 'unit_number_or_id'],
                'unique_together': {('apartment', 'unit_number_or_id')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_on', models.DateTimeField(auto_now_add=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.unit')),
            ],
        ),
    ]
