# Generated by Django 6.0.2 on 2026-03-18 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartmentamenitydistance',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_distances', to='properties.apartment'),
        ),
        migrations.AlterUniqueTogether(
            name='keyamenity',
            unique_together={('amenity_type', 'name')},
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreements', to='properties.apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='lease_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments_using', to='properties.leaseagreement'),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.lease'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='properties.lease'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.lease'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.apartment'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='apartmentamenitydistance',
            unique_together={('apartment', 'amenity_type')},
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['verification_status'], name='properties__verific_92461b_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['landlord'], name='properties__landlor_769cfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('apartment', 'unit_number_or_id')},
        ),
    ]
