# Generated by Django 5.0.4 on 2026-02-14 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="verification_notes",
        ),
        migrations.AlterField(
            model_name="apartment",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("NOT_REQUESTED", "Not Requested"),
                    ("PENDING", "Pending"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="NOT_REQUESTED",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(
                fields=["verification_status"], name="properties__verific_92461b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(
                fields=["landlord"], name="properties__landlor_769cfa_idx"
            ),
        ),
    ]
