# Generated by Django 5.0.4 on 2026-02-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_apartment_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
