# Generated by Django 5.0.4 on 2026-02-25 05:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_apartment_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='lease_agreement_document_url',
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='lease_agreements/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_hash', models.CharField(help_text='SHA-256 hash of the document', max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreements', to='properties.apartment')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='lease_agreement',
            field=models.ForeignKey(blank=True, help_text='Latest lease agreement document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments_using', to='properties.leaseagreement'),
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['apartment', '-version'], name='properties__apartme_925b03_idx'),
        ),
    ]
