# Generated by Django 5.0.4 on 2026-03-03 04:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_apartment_lease_agreement_document_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amenity_type', models.CharField(choices=[('SCHOOL', 'School'), ('MARKET', 'Market'), ('HOSPITAL', 'Hospital'), ('ROAD', 'Road'), ('BUS_STOP', 'Bus Stop'), ('PHARMACY', 'Pharmacy'), ('BANK', 'Bank'), ('RESTAURANT', 'Restaurant'), ('PARK', 'Park'), ('GYM', 'Gym'), ('UNIVERSITY', 'University'), ('SHOPPING_MALL', 'Shopping Mall')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Key Amenities',
                'unique_together': {('amenity_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApartmentAmenityDistance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amenity_type', models.CharField(choices=[('SCHOOL', 'School'), ('MARKET', 'Market'), ('HOSPITAL', 'Hospital'), ('ROAD', 'Road'), ('BUS_STOP', 'Bus Stop'), ('PHARMACY', 'Pharmacy'), ('BANK', 'Bank'), ('RESTAURANT', 'Restaurant'), ('PARK', 'Park'), ('GYM', 'Gym'), ('UNIVERSITY', 'University'), ('SHOPPING_MALL', 'Shopping Mall')], max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=5)),
                ('nearest_name', models.CharField(blank=True, help_text='Name of the nearest amenity of this type', max_length=255)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_distances', to='properties.apartment')),
            ],
            options={
                'ordering': ['amenity_type'],
                'unique_together': {('apartment', 'amenity_type')},
            },
        ),
    ]
