# Generated by Django 6.0.2 on 2026-03-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_keyamenity_apartmentamenitydistance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leaseagreement',
            name='properties__apartme_925b03_idx',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='lease_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments_using', to='properties.leaseagreement'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartmentamenitydistance',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='apartmentamenitydistance',
            name='nearest_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
    ]
