# Generated by Django 5.0.4 on 2026-06-09 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_apartment_exterior_image_apartment_virtual_tour_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='units/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])]),
        ),
    ]
