# Generated by Django 5.0.4 on 2026-06-13 05:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_add_unit_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Unit video tour (max 100MB)', max_length=255, null=True, verbose_name='video'),
        ),
    ]
