# Generated by Django 5.0.4 on 2026-07-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_unit_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Security/rent deposit amount (e.g. 1 or 2 months rent)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='electricity_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Electricity/KPLC deposit amount in KES', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='electricity_rate',
            field=models.CharField(blank=True, help_text="Electricity billing info e.g. 'Token meter' or 'KES 20 per unit'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='water_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Water deposit amount in KES', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='water_rate',
            field=models.CharField(blank=True, help_text="Water billing info e.g. 'KES 150 per unit' or 'Included in rent'", max_length=100, null=True),
        ),
    ]
