# Generated by Django 5.0.4 on 2026-08-23 19:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_unit_deposit_amount_unit_electricity_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='exterior_video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Uploaded video showing the outside/exterior of the property (max 100MB)', max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='unit',
            name='agreement_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tenancy/lease agreement processing fee in KES, paid on move-in', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text='External 360 tour URL (e.g. Matterport)'),
        ),
    ]
