# Generated by Django 6.0.2 on 2026-02-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
