# Generated by Django 5.0.4 on 2026-05-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallettransaction_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('COMMISSION_DEDUCTION', 'Commission Deduction'), ('REFUND', 'Refund'), ('SUBSCRIPTION', 'Subscription')], max_length=30),
        ),
    ]
