# Generated by Django 5.0.4 on 2026-05-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('LANDLORD', 'Landlord'), ('PLATFORM', 'Platform')], default='PLATFORM', max_length=20),
        ),
    ]
