# Generated by Django 5.0.4 on 2026-05-06 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_apartment_exterior_image_apartment_virtual_tour_url_and_more'),
        ('wallet', '0007_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='properties.apartment'),
        ),
    ]
