# Generated by Django 5.0.4 on 2026-06-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_subscription_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
