# Generated by Django 5.0.4 on 2026-02-25 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0004_remove_apartment_lease_agreement_document_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lease_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.leaseagreement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='lease_agreement_acknowledged',
            field=models.BooleanField(default=False, help_text='Whether tenant acknowledged the lease agreement'),
        ),
    ]
