# Generated by Django 5.0.4 on 2026-06-16 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('notify_booking_requests', models.BooleanField(default=True)),
                ('notify_booking_confirmations', models.BooleanField(default=True)),
                ('notify_user_registrations', models.BooleanField(default=True)),
                ('notify_property_verifications', models.BooleanField(default=True)),
                ('notify_tour_requests', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('USER_REGISTRATION', 'New User Registration'), ('USER_VERIFICATION', 'User Verification'), ('USER_ROLE_CHANGE', 'Role Change'), ('BOOKING_REQUEST', 'Booking Request'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_PAYMENT', 'Payment Received'), ('APARTMENT_SUBMITTED', 'Apartment Submitted'), ('APARTMENT_VERIFIED', 'Apartment Verified'), ('APARTMENT_REJECTED', 'Apartment Rejected'), ('APARTMENT_APPROVED', 'Apartment Approved'), ('TOUR_REQUEST', 'Tour Request'), ('TOUR_CONFIRMED', 'Tour Confirmed'), ('TOUR_CANCELLED', 'Tour Cancelled'), ('GENERAL', 'General')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, help_text="e.g., 'Booking', 'Apartment', 'User'", max_length=50, null=True)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx')],
            },
        ),
    ]
